### ISSUE TITLE
食材登録画面で食材が登録されない

### ISSUE THREAD

**Issue by kageyasai2** [kageyasai2/A_Project#47]

**Comment by NAKKA-K** [comment]
タスクボードにバグタスクとして張り出してるやつやな。
フロントのバグ

**Comment by kageyasai2** [comment]
コントローラーに送られてきたデータを確認すると配列の最初に空文字のデータが送られていた
恐らくfood_register.erb 18~23行目のデータも一緒に送られているためだと思う

**Comment by NAKKA-K** [comment]
内容はもう解決済み。
あとはこうし君がpushするだけの状態
